POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/013d1e0c-ce74-49c6-ac11-ab32386001b2/attendees
Content-Type: application/json

{
  "name": "Victor Matheus",
  "email": "victormatheus507@gmail.com"
}